apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-frontend
  namespace: tracking-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-frontend
  template:
    metadata:
      labels:
        app: customer-frontend
    spec:
      containers:
      - name: customer
        image: 088310115913.dkr.ecr.us-east-1.amazonaws.com/customer-frontend:latest
        ports:
        - containerPort: 80
